from typing import Protocol, runtime_checkable


@runtime_checkable
class Authenticable(Protocol):
    def login(self) -> str: ...
    def password_hash(self) -> str: ...
    def is_active(self) -> bool: ...
